### PR TITLE
Move to use op-scim-helm chart

### PR DESCRIPTION
**Pull request by devillexio**
In this PR we update the GCP marketplace configuration to use the chart defined in [1Password/op-scim-helm](https://github.com/1Password/op-scim-helm).

The most significant changes are related to no longer duplicating the Helm chart configuration from `1Password/op-scim-helm`. We are instead depending on this chart by creating a [wrapper chart](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md#part-1b-optional-creating-a-wrapper-chart). With this in mind we removed much of the logic involved in creating custom SCIM bridge and redis images.

We have also updated the project and chart `README.md` files.

To test:
1. Make sure you are in the `op-scim-bridge` folder (same as `Makefile`)
2. Create an image using a test tag: `REGISTRY="gcr.io/op-scim-bridge" TAG=t<test-tag-name> make app/build`
3. Verify the test deployer: `TAG=<test-tag-name> make app/test`
4. Ensure that the verify succeeds
6. Install the test deployer on a GCP cluster:
     ```
    mpdev install --deployer=gcr.io/op-scim-bridge/op-scim-bridge/deployer:<test-tag-name> --parameters='{"name": "op-scim-bridge", "namespace": "op-scim-bridge", "accountDomain": "testing.1password.com", "scim.serviceAccount": "op-scim-bridge-deployer-sa" }'
    ```
7. Ensure that the install succeeds and that the application (and dependencies) are running without error

Also please review that the instructions in the updated `README.md` files to see if they are clear.

### CODE REVIEW

**Comment by devillexio** [comment]
Note that there is currenntly an issue with `mpdev verify`. The application and dependencies are deployed and started successfully, but the test script never cleans up a few service accounts.

On my environment it keeps looping the following set of lines:
```
INFO Checking if serviceaccounts,roles,rolebindings were deleted
Using /opt/kubectl/1.22/kubectl (server=1.22)
INFO Remaining: 3
INFO ServiceAccount/apptest-zea8czj8-op-scim-bridge
ServiceAccount/apptest-zea8czj8-redis
ServiceAccount/default
```

**Comment by devillexio** [comment]
I think the parameters I'm passing to `mpdev verify` are not being applied. I'm basing this assumption off of the error summary from my latest run:
```
=== ERROR SUMMARY ===
ERROR Some service accounts or roles were not deleted

Error events found in namespace "apptest-vbtbpkmg"
LAST SEEN   TYPE      REASON             OBJECT                                                 MESSAGE
11m         Warning   FailedCreate       job/apptest-vbtbpkmg-cleanup-27635995                  Error creating: pods "apptest-vbtbpkmg-cleanup-27635995-" is forbidden: error looking up service account apptest-vbtbpkmg/op-scim-bridge-deployer-sa: serviceaccount "op-scim-bridge-deployer-sa" not found
10m         Warning   FailedCreate       job/apptest-vbtbpkmg-cleanup-27635996                  Error creating: pods "apptest-vbtbpkmg-cleanup-27635996-" is forbidden: error looking up service account apptest-vbtbpkmg/op-scim-bridge-deployer-sa: serviceaccount "op-scim-bridge-deployer-sa" not found
12m         Warning   FailedScheduling   pod/apptest-vbtbpkmg-op-scim-bridge-6955768594-nkwkk   0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
11m         Warning   BackOff            pod/apptest-vbtbpkmg-op-scim-bridge-6955768594-nkwkk   Back-off restarting failed container
12m         Warning   FailedScheduling   pod/apptest-vbtbpkmg-redis-master-66f87d9b5d-8tfft     0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
=====================

=== VERIFICATION STATUS ===
FAILED
===========================
```

**Comment by alicethorne-ab** [comment]
The `componentKinds` list in `application.yaml` didn't contain a `ServiceAccount` field, meaning `mpdev` didn't know to delete it at the end of the day, as it'd just skip the "delete service accounts" step, even though it still depends on all resources being deleted. That should be fixed now.

**Comment by devillexio** [comment]
@grellyd, I'm happy for you to be tagged as reviewer for an FYI, since you are working on the latest SCIM bridge release.

I tagged @alicethorne-ab as a primary reviewer as she has a lot of context on this project and the GCP marketplace deployer in general.

**Pull request merged**
