### PR TITLE
Fix version and public IP

### LINKED ISSUE #54: SCIM bridge public IP address no longer displayed after marketplace deployment
After moving to the Helm chart the marketplace application no longer shows the SCIM bridge public IP address.

The symptoms are:
1. the application state remains in "Some components are pending", and
2. the "1Password SCIM bridge public IP" is not populated under the "SCIM bridge info" section and the following message is displayed instead: "Referenced object not found" (see screenshot below)

SCIM bridge info - Referenced object not found

The SCIM bridge deployment still succeeds, but the public IP address is not shown as expected. It can still be obtained from the deployed SCIM bridge load balancer service, but this does not align with our support documentation on how to deploy the SCIM bridge.

### PR DESCRIPTION
**Pull request by devillexio**
This PR resolves the issue where the public IP address was no longer being obtained from the SCIM bridge service, and displayed in the SCIM bridge info section.

The root cause of the issue is that with the migration to using the `1Password/op-scim-helm` Helm chart we neglected to update the reference to the service name.

To test:

1. Ensure your cluster doesn't have any existing applications: `kubectl delete application --all`
2. Wait for the resources to be cleaned up, including the SCIM bridge load balancer service
3. From the `op-scim-bridge` folder (where the `Makefile` is), build and tag a test image:
     ```
     REGISTRY="gcr.io/op-scim-bridge" TAG=test-fix-for-54 make app/build
     ```
4. Install the test tag with mpdev:
    ```
    mpdev install --deployer=gcr.io/op-scim-bridge/op-scim-bridge/deployer:test-fix-for-54 --parameters='{"name": "op-scim-bridge-1", "namespace": "op-scim-bridge", "accountDomain": "example.1password.com" }'
    ```
5. Ensure the application installs correctly and that the deployer creates the correct resources.
6. Ensure that the SCIM bridge service public IP address is displayed under the "SCIM bridge info" section.
7. Ensure that clicking the IP address opens the deployed SCIM bridge UI.

Resolves #54.

### CODE REVIEW

**Comment by laughingman-hass** [comment]
Working as expected
Screen Shot 2022-08-04 at 11 33 56

**Review by laughingman-hass — DISMISSED** [review]
Looks good. Was wondering if its worth documenting the different version tags and what they mean in the README or internal docs somewhere? 🤔

**Comment by devillexio** [comment]
@laughingman-hass 

Re:

> Was wondering if its worth documenting the different version tags and what they mean in the README or internal docs somewhere? 🤔

I did do this for DO and the op-scim-helm project. For this one the only real versions of importance are the Chart `appVersion` and the schema `publishedVersion`. The Chart `version` is completely ignored for GCP.

I think over time we may find some improvements to the way we document these, but I'd like a few folks to go through these docs and provide feedback.

**Comment by devillexio** [comment]
By commenting out everything in the Chart values.yaml I have broken the `mpdev verify`. I am looking into fixing it without unnecessarily overriding any values defined in the subchart.

**Comment by devillexio** [comment]
In addition to the test described in the description, you can also do a `mpdev verify` to confirm it still works. This process is covered in the `README.md`.

But as a shortcut, mpdev verify can be run with the following:
```bash
REGISTRY="gcr.io/op-scim-bridge" TAG=test-mpdev-verify make app/build && \
echo "waiting for 5 seconds" && \
sleep 5 && \
mpdev verify --deployer=gcr.io/op-scim-bridge/op-scim-bridge/deployer:test-mpdev-verify --parameters='{"name": "mpdev", "accountDomain": "example.1password.com" }'
```

**Comment by laughingman-hass** [comment]
Redone the previous tests and working as expected, along with `mdev verify` passing
Screen Shot 2022-08-04 at 18 55 12

**Review by laughingman-hass — APPROVED** [review]

**Pull request merged**
